version: 1
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
  test: {}
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world